// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBySbAOtvKVgzslkYJmpkEOszuryBK564Y',
    appId: '1:797279245809:web:78bf54704ce93ae00f2050',
    messagingSenderId: '797279245809',
    projectId: 'wildscan-79e9c',
    authDomain: 'wildscan-79e9c.firebaseapp.com',
    databaseURL: 'https://wildscan-79e9c-default-rtdb.firebaseio.com',
    storageBucket: 'wildscan-79e9c.firebasestorage.app',
    measurementId: 'G-N877VRZQEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmSTPptwlXdPEwE5_X4JA83uriTo6lePo',
    appId: '1:797279245809:android:0dbc414bfb24c8fb0f2050',
    messagingSenderId: '797279245809',
    projectId: 'wildscan-79e9c',
    databaseURL: 'https://wildscan-79e9c-default-rtdb.firebaseio.com',
    storageBucket: 'wildscan-79e9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD8O2ugrv7aJgC6pcQIUbFN5s1BsHaWD0',
    appId: '1:797279245809:ios:3b5cc03bd9b723120f2050',
    messagingSenderId: '797279245809',
    projectId: 'wildscan-79e9c',
    databaseURL: 'https://wildscan-79e9c-default-rtdb.firebaseio.com',
    storageBucket: 'wildscan-79e9c.firebasestorage.app',
    androidClientId: '797279245809-vt0oshup65c0o0s6n9skihbkeh16ih8t.apps.googleusercontent.com',
    iosClientId: '797279245809-3ki605m79koo5bm90ps78muff5i990e3.apps.googleusercontent.com',
    iosBundleId: 'com.example.wildscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD8O2ugrv7aJgC6pcQIUbFN5s1BsHaWD0',
    appId: '1:797279245809:ios:3b5cc03bd9b723120f2050',
    messagingSenderId: '797279245809',
    projectId: 'wildscan-79e9c',
    databaseURL: 'https://wildscan-79e9c-default-rtdb.firebaseio.com',
    storageBucket: 'wildscan-79e9c.firebasestorage.app',
    androidClientId: '797279245809-vt0oshup65c0o0s6n9skihbkeh16ih8t.apps.googleusercontent.com',
    iosClientId: '797279245809-3ki605m79koo5bm90ps78muff5i990e3.apps.googleusercontent.com',
    iosBundleId: 'com.example.wildscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBySbAOtvKVgzslkYJmpkEOszuryBK564Y',
    appId: '1:797279245809:web:ec20748f93d161460f2050',
    messagingSenderId: '797279245809',
    projectId: 'wildscan-79e9c',
    authDomain: 'wildscan-79e9c.firebaseapp.com',
    databaseURL: 'https://wildscan-79e9c-default-rtdb.firebaseio.com',
    storageBucket: 'wildscan-79e9c.firebasestorage.app',
    measurementId: 'G-BEZP1P6H08',
  );

}